### PR TITLE
Update to Anki 2.1.54

### PR DESCRIPTION
**Pull request by dae**
I've applied some of the changes to the main repo, reducing the amount of patches required. I've also squashed the earlier commits from David into the commit that moves things into this repo, as that made it easier to rebase over the latest code. Once you update this repo to the latest main from ankitects, it should show only two commits.

Posting this for reference; recommend you do a fast-forward merge into a new branch, as that way the commit hash will not need to be updated twice in the -Backend repo.

### CODE REVIEW

**Comment by mikehardy** [comment]
Ah, cool. Will look through these

https://github.com/ankidroid/anki/pull/3/commits/dd94655d56f35950781b6bc7d7ebe833f26003cd seems to indicate versioning should be 2.1.55 though yes? (here as branch name, and in Anki-Android-Backend/Anki-Android as version suffix? 

commit hash for rslib/anki still would be same though, 2.1.55 is in the file and just used in other layers

**Comment by mikehardy** [comment]
perhaps since 2.1.55 is untagged it's still unreleased "preparing for 2.1.55" in your mind? That's fine either way, commit hashes are where things really happen...

**Comment by mikehardy** [comment]
GitHub Web UI does not support fast-forward merges https://stackoverflow.com/questions/60597400/how-to-do-a-fast-forward-merge-on-github

On the command line, assuming you have "origin" set up as a remote (to a personal fork), "ankitects" set up as a remote, and you have "ankidroid" set up as a remote, it looked like this:

```bash
git co main
git fetch ankitects
git rebase ankitects/main
git push origin
git push ankidroid
git co -b ankidroid-2.1.54 # this works because it is unambiguous to this point, it only existed in ankitects remote to start
git reset --hard 67e4edc # that was the most recent commit hash on ankitects/main for this PR
git push ankidroid # this gets us a clean ankidroid-2.1.54 branch at the divergence point, in our repo now
# Now on this PR edit it and change it to target our new branch, poof 2 commits as indicated
git merge --ff-only upstream/ankidroid-2.1.54  # now we have identical commit hashes from the PR, merged
git push ankidroid
```

Now we've pushed the commits here without modifying their commit hashes, so the commit hash in Anki-Android-Backend is stable

From a git perspective this is not really deep voodoo but I'm just noting it here in case my future self needs it or someone that hasn't had to abuse git as much as I have walks in and wants to do it the next time :-). "git for fun and profit"

**Comment by mikehardy** [comment]
Nice and clean @dae - down to 2 commits here, the rust lib vision of more shared code with more effort just going in to that one shared codebase is happening

**Comment by dae** [comment]
It's not technically 2.1.54, but is fairly close - the only changes since the release were a small translation update, the version number bump, and the AnkiDroid-specific changes/renaming of a module name in the Rust code. Ideally we'd stick to the release tags in the future, but in this case I didn't add the Android changes until after the release was made.

**Pull request merged**
